project/audio_lessons/urls.py
from django.urls import path



from . import views


app_name = "audio_lessons"

urlpatterns = [
    # path("", views.level_selection, name="level_selection"),
    path("", views.audio_list, name="audio_list"),
    path("play-list", views.get_play_list, name="play_list"),
]

project/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("audio_lessons.urls", namespace="audio_lessons")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username

project/audio_lessons/models.py
from django.db import models


class AudioLessonLevel(models.Model):
    level = models.CharField(max_length=100, null=False, blank=False)
    
    def __str__(self):
        return self.level
    

class AudioLesson(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)
    level = models.ForeignKey(AudioLessonLevel, on_delete=models.PROTECT)
    audio = models.FileField(upload_to="audio/", unique=True)
    audio_thumbnail = models.ImageField(upload_to="images/audio_images/",default="images/audio_images/default.png")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

project/accounts/forms.py
from django.contrib.auth.forms import AdminUserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(AdminUserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")

project/accounts/views.py
from django.shortcuts import render

# Create your views here.

project/audio_lessons/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import F


from .models import AudioLesson

def level_selection(request):
    return render(request, "audio_lessons/level_selection.html")

def audio_list(request):
    audio_files = AudioLesson.objects.all()
    context = {
        "audio_files": audio_files
    }
    #  <header name="Accept-Ranges" value="bytes"> добавь к nginx
    return render(request, "audio_lessons/audio_list.html", context)

def get_play_list(request):
    audio_files = list(AudioLesson.objects.values(title=F("name"), file=F("audio"),))
    for i, item in enumerate(audio_files):
        item.update({"howl": ""})
    return JsonResponse(audio_files, safe=False)

project/templates/audio_lessons/audio_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/audio_player/palyer_styles.css' %}" />
  <div class="container">
    {% for audio in audio_files %}
      <div class="card my-3">
        <div class="row g-0">
          <div class="col-2 col-md-2">
            <img src="{% thumbnail audio.audio_thumbnail 'audio_image' %}" class="d-flex audio-card h-100 img-fluid img-thumbnail rounded-start" alt="{{ song.songName }}"/>
            {% comment %} <img src="media/{{ audio.audio_thumbnail }}" class="d-flex audio-card h-100 img-fluid img-thumbnail rounded-start" alt="{{ song.songName }}"/> {% endcomment %}
          </div>
          <div class="col-8 col-md-8">
            <div class="card-body">
              <p class="card-title fs-6 text">{{ audio.name }}</p>
            </div>
          </div>
          <div class="col-2 col-md-2">
            <div class="play-button d-flex h-100 justify-content-center align-items-center">
              <i class="btn bi bi-play-circle fs-1 play-btn" data-bs-toggle="modal" data-bs-target="#exampleModal" data-sound-index="{{forloop.counter0}}"></i>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% include 'audio_lessons/partitions/modal.html' %}
{% endblock %}
{% block javascript %}

{% endblock %}

project/templates/audio_lessons/level_selection.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block content %}
  
{% endblock %}

project/templates/audio_lessons/partitions/modal.html
{% load static %}

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Player</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
                {% include "audio_lessons/player.html" %}
        
      </div>
    </div>
  </div>
</div>

project/templates/audio_lessons/player.html
{% load static %}


<!-- Top Info -->
<div id="title">
  <span id="track"></span>
  <hr />
  <div id="timer">0:00</div>
  <div id="duration">0:00</div>
</div>

<!-- Controls -->
<div class="controlsOuter">
  <div class="controlsInner">
    <div id="loading"></div>
    <div class="btn" id="playBtn"></div>
    <div class="btn" id="pauseBtn"></div>
    <div class="btn" id="prevBtn"></div>
    <div class="btn" id="nextBtn"></div>
  </div>
  <div class="btn" id="playlistBtn"></div>
  <div class="btn" id="volumeBtn"></div>
</div>

<!-- Progress -->
<div id="waveform"></div>
<div id="bar"></div>
<div id="progress"></div>

<!-- Playlist -->
<div id="playlist">
  <div id="list"></div>
</div>

<!-- Volume -->
<div id="volume" class="fadeout">
  <div id="barFull" class="bar"></div>
  <div id="barEmpty" class="bar"></div>
  <div id="sliderBtn"></div>
</div>

<!-- Scripts -->
{% comment %} <script src="../../src/howler.core.js"></script> {% endcomment %}
<script src="{% static 'js/audio_player/howler.core.js' %}"></script>
<script src="{% static 'js/audio_player/siriwave.js' %}"></script>
<script type="module" src="{% static 'js/audio_player/player.js' %}"></script>

project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">


    <link rel="stylesheet" href="https://cdn.datatables.net/2.3.2/css/dataTables.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.4/css/responsive.dataTables.css">
    <link href="https://cdn.datatables.net/columncontrol/1.0.5/css/columnControl.dataTables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/datetime/1.5.5/css/dataTables.dateTime.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/3.2.3/css/buttons.dataTables.css">
    
    
    <title>
      {% block title %}

      {% endblock %}
    </title>
  </head>
  <body>
    <div id="main_container">
      {% include 'boootstrap_bar/bar.html' %}
      
      <div id="top-menu-fix"></div>
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="{% static 'js/htmx/htmx.min.js' %}"></script>


    
    <script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.4/js/dataTables.responsive.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.4/js/responsive.dataTables.js"></script>
    
    <script src="https://cdn.datatables.net/columncontrol/1.0.5/js/dataTables.columnControl.min.js"></script>
    <script src="https://cdn.datatables.net/columncontrol/1.0.5/js/columnControl.dataTables.js"></script>
    <script src="https://cdn.datatables.net/datetime/1.5.5/js/dataTables.dateTime.min.js"></script>


    <script src="https://cdn.datatables.net/buttons/3.2.3/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.2.3/js/buttons.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.2.3/js/buttons.html5.min.js"></script>

    {% comment %} <script src="https://cdn.jsdelivr.net/npm/howler@2.2.4/dist/howler.min.js"></script> {% endcomment %}

    

    
    
    
    {% block javascript %}
    {% endblock  %}
  </body>
</html>

project/templates/boootstrap_bar/bar.html
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body fixed-top" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Example App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          {% comment %} <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "audio_lessons:level_selection" %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "audio_lessons:audio_list" %}">Audio list</a>
          </li> {% endcomment %}
        
        </ul>
      </div>
    </div>
  </nav>